// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab1.Models.Context;

#nullable disable

namespace Bai2.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240106165557_no1")]
    partial class no1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lab2_2.Model.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)");

                    b.Property<string>("DChi")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)");

                    b.Property<string>("Honv")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double?>("Luong")
                        .HasColumnType("float");

                    b.Property<string>("MaNQL")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<int>("PHG")
                        .HasColumnType("int");

                    b.Property<string>("Phai")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)");

                    b.Property<string>("TenLot")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("lab2_2.Model.ThanNhan", b =>
                {
                    b.Property<string>("Ma_NV")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)");

                    b.Property<string>("TenTN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgSinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Phai")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Ma_NV", "TenTN");

                    b.ToTable("ThanNhan", (string)null);
                });

            modelBuilder.Entity("lab2_2.Model.ThanNhan", b =>
                {
                    b.HasOne("lab2_2.Model.NhanVien", "NhanVien")
                        .WithMany("thanNhans")
                        .HasForeignKey("Ma_NV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("lab2_2.Model.NhanVien", b =>
                {
                    b.Navigation("thanNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
